---
- name: Update all packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install useful utilities
  apt:
    name:
      - vim
      - git
      - curl
    state: present

- name: Install firewalld
  apt:
    name: firewalld
    state: present

- name: Enable and start firewalld
  service:
    name: firewalld
    state: started
    enabled: true
